import Head from "next/head"
import { useRouter } from "next/router"
import { FormEvent, useEffect, useState } from "react"
import Button from "~/components/atoms/Button"
import Input from "~/components/atoms/Input"
import Navbar from "~/components/atoms/NavBar"
import { api } from "~/utils/api"

const Detail = () => {
  const { query, push } = useRouter()

  const post = api.post.getById.useQuery(
    { id: query.id ?? "" },
    {
      onSuccess: (data) => {
        setTitle(data.title)
        setContent(data.content)
      },
    }
  )
  const { mutate, error } = api.post.create.useMutation({
    onSuccess: (data) => {
      push("/")
    },
  })

  const [title, setTitle] = useState("")
  const [content, setContent] = useState("")

  const onSubmit = (e: FormEvent) => {
    // e.preventDefault()
    // mutate({
    //   title,
    //   content,
    // })
    // console.log(error?.data?.zodError?.fieldErrors.content)
  }
  return (
    <>
      <Head>
        <title>Simple Posts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="m-auto max-w-4xl">
        <Navbar />
        <main className="mt-4 grid grid-cols-4 gap-4">
          <h1>Detail {query.id}</h1>
          {!post.data && <h2>Data not found</h2>}
          <form
            className="flex flex-col items-center space-y-2"
            onSubmit={onSubmit}
          >
            <Input name="Title" value={title} onChange={(v) => setTitle(v)} />
            <Input
              name="Content"
              value={content}
              onChange={(v) => setContent(v)}
            />

            <Button name="Submit" />
          </form>
          {error?.data?.zodError?.fieldErrors.content && (
            <span className="rounded-lg border border-red-600 p-2 text-red-600">
              {error.data.zodError.fieldErrors.content}
            </span>
          )}
        </main>
      </div>
    </>
  )
}

export default Detail
